### PR TITLE
Add Mask Fit plugin

### PR DESCRIPTION
**Pull request by paolobiagini**
# Submit your project for inclusion in XD-Awesome

Hey! We're happy you want to submit your project to XD-Awesome. Please create a pull request and ensure that you fill out the following template:

## **Mask Fit**

**Description of your project:** A command-like plugin that allows fitting images to their mask

**Link to your project:** https://github.com/paolobiagini/xd-mask-fit

**License:** MIT

**Category:** Source Plugins

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by dkstevekwak** [comment]
@paolobiagini  one feature request/sugggestion - could you please make it work with a group object as well?

**Comment by paolobiagini** [comment]
I wish I could but I don’t know how to manage responsive resize since it is on by default.Anyway, I will make some test.Thank you!@paolobiagini  one feature request/sugggestion - could you please make it work with a group object as well?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.









Paolo Biaginiwww.paolobiagini.com

**Comment by dkstevekwak** [comment]
@paolobiagini ah yes. Currently, you can't programmatically turn off responsive resizing..

**Comment by paolobiagini** [comment]
I knew, unfortunately. That's why I have not implemented group resize yet.



   @paolobiagini ah yes. Currently, you can't programmatically turn off responsive resizing..

   —
   You are receiving this because you were mentioned.
   Reply to this email directly, view it on GitHub, or mute the thread.

   Paolo Biagini
   www.paolobiagini.com

**Pull request merged**
